import ExcelJS from 'exceljs';
import PDFDocument from 'pdfkit';

// Real PDF/Excel exporters for the Reports & Analytics module — the
// previous state only had a client-side CSV button; "email me this report"
// used to send a JSON dump instead of a file. Both builders here take the
// exact same {summary, rows} shape services/reportData.ts produces, so a
// scheduled delivery, an on-demand download, and an emailed export always
// show the same numbers.

export interface ReportExportMeta {
  title: string;
  tenantName: string;
  generatedByName: string;
  generatedByEmail: string;
  generatedAt: Date;
  timezone: string;
  filtersDescription: string; // human-readable summary, e.g. "Jul 1 - Jul 30, 2026 · Department: Sales"
}

export async function buildReportExcel(rows: any[], summary: Record<string, any>, meta: ReportExportMeta): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = meta.generatedByName || meta.generatedByEmail;
  workbook.created = meta.generatedAt;

  const summarySheet = workbook.addWorksheet('Summary');
  summarySheet.columns = [{ width: 28 }, { width: 40 }];
  summarySheet.addRow([meta.title]).font = { bold: true, size: 14 };
  summarySheet.addRow([meta.tenantName]);
  summarySheet.addRow([`Generated by ${meta.generatedByName || meta.generatedByEmail} on ${meta.generatedAt.toLocaleString()} (${meta.timezone})`]);
  summarySheet.addRow([`Filters: ${meta.filtersDescription}`]);
  summarySheet.addRow([]);
  summarySheet.addRow(['Metric', 'Value']).font = { bold: true };
  for (const [key, value] of Object.entries(summary || {})) {
    summarySheet.addRow([key, value]);
  }

  const dataSheet = workbook.addWorksheet('Data');
  if (rows.length > 0) {
    const headers = Object.keys(rows[0]);
    dataSheet.columns = headers.map((h) => ({ header: h, key: h, width: Math.max(12, Math.min(30, h.length + 4)) }));
    dataSheet.getRow(1).font = { bold: true };
    dataSheet.addRows(rows);
  } else {
    dataSheet.addRow(['No data for the selected filters.']);
  }

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

const PAGE_MARGIN = 40;
const ROW_HEIGHT = 16;

export async function buildReportPdf(rows: any[], summary: Record<string, any>, meta: ReportExportMeta): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: PAGE_MARGIN, size: 'A4', layout: rows.length > 0 && Object.keys(rows[0]).length > 6 ? 'landscape' : 'portrait' });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header
    doc.fontSize(16).font('Helvetica-Bold').text(meta.title, { align: 'left' });
    doc.fontSize(9).font('Helvetica').fillColor('#64748b');
    doc.text(meta.tenantName);
    doc.text(`Generated by ${meta.generatedByName || meta.generatedByEmail} on ${meta.generatedAt.toLocaleString()} (${meta.timezone})`);
    doc.text(`Filters: ${meta.filtersDescription}`);
    doc.moveDown(0.5);

    // KPI summary
    doc.fontSize(10).fillColor('#0f172a').font('Helvetica-Bold').text('Summary');
    doc.font('Helvetica').fontSize(9).fillColor('#334155');
    const summaryEntries = Object.entries(summary || {});
    for (let i = 0; i < summaryEntries.length; i += 3) {
      const line = summaryEntries.slice(i, i + 3).map(([k, v]) => `${k}: ${v}`).join('    ');
      doc.text(line);
    }
    doc.moveDown(0.75);

    // Table
    if (rows.length === 0) {
      doc.fontSize(10).fillColor('#64748b').text('No data for the selected filters.');
    } else {
      const headers = Object.keys(rows[0]);
      const pageWidth = doc.page.width - PAGE_MARGIN * 2;
      const colWidth = pageWidth / headers.length;

      const drawHeaderRow = (y: number) => {
        doc.fontSize(8).font('Helvetica-Bold').fillColor('#ffffff');
        doc.rect(PAGE_MARGIN, y, pageWidth, ROW_HEIGHT).fill('#334155');
        doc.fillColor('#ffffff');
        headers.forEach((h, i) => {
          doc.text(String(h), PAGE_MARGIN + i * colWidth + 2, y + 4, { width: colWidth - 4, height: ROW_HEIGHT, ellipsis: true });
        });
      };

      let y = doc.y;
      drawHeaderRow(y);
      y += ROW_HEIGHT;

      doc.font('Helvetica').fontSize(8);
      rows.forEach((row, rowIdx) => {
        if (y + ROW_HEIGHT > doc.page.height - PAGE_MARGIN) {
          doc.addPage();
          y = PAGE_MARGIN;
          drawHeaderRow(y);
          y += ROW_HEIGHT;
          doc.font('Helvetica').fontSize(8);
        }
        if (rowIdx % 2 === 1) {
          doc.rect(PAGE_MARGIN, y, pageWidth, ROW_HEIGHT).fill('#f8fafc');
        }
        doc.fillColor('#0f172a');
        headers.forEach((h, i) => {
          doc.text(String(row[h] ?? '-'), PAGE_MARGIN + i * colWidth + 2, y + 4, { width: colWidth - 4, height: ROW_HEIGHT, ellipsis: true });
        });
        y += ROW_HEIGHT;
      });
    }

    // Page numbers + confidentiality footer on every page
    const pageCount = doc.bufferedPageRange().count;
    for (let i = 0; i < pageCount; i++) {
      doc.switchToPage(i);
      doc.fontSize(7).fillColor('#94a3b8').text(
        `Confidential — generated by Smart Teams EMS · Page ${i + 1} of ${pageCount}`,
        PAGE_MARGIN,
        doc.page.height - PAGE_MARGIN + 10,
        { align: 'center', width: doc.page.width - PAGE_MARGIN * 2 },
      );
    }

    doc.end();
  });
}
