import { Router } from 'express';
import { eq, and, desc } from 'drizzle-orm';
import { db, schema } from '../../db';
import { sendServerError } from '../utils/errors';
import { logger } from '../../logger';
import { authenticate } from '../middleware/authenticate';
import { hasPrivilege } from '../auth/rbac';
import { sendEmail } from '../../mail.js';
import { buildReportData, type ReportFilters } from '../services/reportData';
import { buildCsv } from '../services/reportExport';
import { buildReportExcel, buildReportPdf, type ReportExportMeta, type ReportColumnMeta, type ReportSummaryFieldMeta } from '../services/reportFileExport';
import { logToAuditLedger } from '../services/audit';
import { tenantDateLabel, tenantDateTimeLabel } from '../services/tenantTime';

import { sanitizeReportColumns } from '../utils/reportColumnAllowlist';

export const router = Router();

function parseFiltersFromQuery(req: any): ReportFilters {
  const type = (req.query.type as string) || 'attendance';
  return {
    type,
    startDate: req.query.startDate as string,
    endDate: req.query.endDate as string,
    department: req.query.department as string,
    branchId: req.query.branchId ? Number(req.query.branchId) : null,
    employeeId: req.query.employeeId ? Number(req.query.employeeId) : null,
    employeeIds: typeof req.query.employeeIds === 'string' && req.query.employeeIds.length > 0 ? req.query.employeeIds.split(',').map(Number).filter(Boolean) : null,
    status: req.query.status as string,
    search: req.query.search as string,
    wfhOnly: req.query.wfh === 'true',
    lateOnly: req.query.late === 'true',
    overtimeOnly: req.query.overtime === 'true',
    exceptionsOnly: req.query.exceptions === 'true',
    modules: typeof req.query.modules === 'string' && req.query.modules.length > 0 ? req.query.modules.split(',') : undefined,
    columns: sanitizeReportColumns(type, req.query.columns),
  };
}

// Human-readable filter summary for report headers/footers/audit entries —
// "Report Metadata" (generated by/on/filters applied) is one of the things
// every professional report export is expected to show.
function describeFilters(filters: ReportFilters): string {
  const parts: string[] = [];
  if (filters.startDate || filters.endDate) parts.push(`${filters.startDate || '...'} to ${filters.endDate || '...'}`);
  if (filters.department && filters.department !== 'ALL') parts.push(`Department: ${filters.department}`);
  if (filters.branchId) parts.push(`Branch #${filters.branchId}`);
  if (filters.employeeId) parts.push(`Employee #${filters.employeeId}`);
  if (filters.status && filters.status !== 'ALL') parts.push(`Status: ${filters.status}`);
  if (filters.wfhOnly) parts.push('WFH only');
  if (filters.lateOnly) parts.push('Late only');
  if (filters.overtimeOnly) parts.push('Overtime only');
  if (filters.exceptionsOnly) parts.push('Exceptions only');
  if (filters.search) parts.push(`Search: "${filters.search}"`);
  return parts.length > 0 ? parts.join(' · ') : 'No filters applied';
}

async function buildExportMeta(req: any, title: string, filters: ReportFilters): Promise<ReportExportMeta> {
  const tenantRows = await db.select().from(schema.tenants).where(eq(schema.tenants.id, req.user.tenantId)).limit(1);
  const tenant = tenantRows[0];

  let branchLabel = 'All Locations';
  if (filters.branchId) {
    const branchRows = await db.select().from(schema.branches).where(eq(schema.branches.id, filters.branchId)).limit(1);
    if (branchRows[0]) branchLabel = branchRows[0].name;
  }
  const filterChips = [
    { label: 'Department', value: filters.department && filters.department !== 'ALL' ? filters.department : 'All Departments' },
    { label: 'Location', value: branchLabel },
    { label: 'Status', value: filters.status && filters.status !== 'ALL' ? filters.status : 'All' },
  ];

  return {
    title,
    tenantName: tenant?.name || 'Organization',
    tenantAddress: tenant?.reportAddress || null,
    logoUrl: req.query.logo === 'false' ? null : (tenant?.reportLogoUrl || null),
    generatedByName: req.user.name,
    generatedByEmail: req.user.email,
    generatedAt: new Date(),
    timezone: tenant?.timezone || 'Asia/Kolkata',
    filtersDescription: describeFilters(filters),
    filterChips,
    themeId: (req.query.themeId as string) || undefined,
    layoutId: (req.query.layoutId as string) || undefined,
    signatureLine: (req.query.signature as string) || null,
    showWatermark: req.query.watermark === 'true',
    pageSize: (req.query.pageSize as 'A4' | 'Letter') || 'A4',
    orientation: (req.query.orientation as 'auto' | 'portrait' | 'landscape') || 'auto',
  };
}

// Mirrors REPORT_TYPE_CONFIG's columns/summaryFields (apps/admin/src/
// components/reports/reportMetadata.ts) — kept as a small server-side
// constant rather than importing the frontend file into the API build,
// same reasoning as reportFileExport.ts's THEME_COLORS mirror. Used only
// to give the PDF/Excel exports real labels instead of raw row/summary
// object keys.
const REPORT_COLUMNS_BY_TYPE: Record<string, ReportColumnMeta[]> = {
  attendance: [
    { key: 'employeeName', label: 'Employee' }, { key: 'department', label: 'Department' },
    { key: 'date', label: 'Date' }, { key: 'status', label: 'Status' },
    { key: 'checkIn', label: 'Check In' }, { key: 'checkOut', label: 'Check Out' },
    { key: 'lateMins', label: 'Late (mins)' }, { key: 'workingHours', label: 'Working Hours', format: 'hours' },
    { key: 'overtimeHours', label: 'Overtime', format: 'hours' }, { key: 'isWfh', label: 'WFH', format: 'boolean' },
    { key: 'verificationMode', label: 'Attendance Mode' }, { key: 'approvalStatus', label: 'Approval Status' },
    { key: 'notes', label: 'Notes' },
  ],
  overtime: [
    { key: 'employeeName', label: 'Employee' }, { key: 'department', label: 'Department' },
    { key: 'date', label: 'Date' }, { key: 'checkIn', label: 'Check In' }, { key: 'checkOut', label: 'Check Out' },
    { key: 'workingHours', label: 'Working Hours', format: 'hours' }, { key: 'overtimeHours', label: 'Overtime', format: 'hours' },
    { key: 'lateMins', label: 'Late (mins)' },
  ],
  leave: [
    { key: 'employeeName', label: 'Employee' }, { key: 'department', label: 'Department' },
    { key: 'leaveType', label: 'Leave Type' }, { key: 'startDate', label: 'Start Date' }, { key: 'endDate', label: 'End Date' },
    { key: 'daysCount', label: 'Days' }, { key: 'status', label: 'Status' }, { key: 'reason', label: 'Reason' },
    { key: 'appliedOn', label: 'Applied On' },
  ],
  payroll: [
    { key: 'employeeName', label: 'Employee' }, { key: 'department', label: 'Department' },
    { key: 'monthYear', label: 'Period' }, { key: 'grossSalary', label: 'Gross', format: 'currency' },
    { key: 'deductions', label: 'Deductions', format: 'currency' }, { key: 'netSalary', label: 'Net Salary', format: 'currency' },
    { key: 'lopDays', label: 'LOP Days' }, { key: 'status', label: 'Status' },
    { key: 'pfAmount', label: 'PF', format: 'currency' }, { key: 'esiAmount', label: 'ESI', format: 'currency' },
    { key: 'taxAmount', label: 'Tax (TDS)', format: 'currency' }, { key: 'loanRecovery', label: 'Loan/Advance Recovery', format: 'currency' },
    { key: 'bonusPaid', label: 'Bonus/Reimbursement', format: 'currency' },
  ],
  employee: [
    { key: 'employeeId', label: 'Employee ID' }, { key: 'employeeName', label: 'Employee' },
    { key: 'email', label: 'Email' }, { key: 'role', label: 'Role' }, { key: 'department', label: 'Department' },
    { key: 'designation', label: 'Designation' }, { key: 'status', label: 'Status' },
    { key: 'kycStatus', label: 'KYC Status' }, { key: 'joinedDate', label: 'Joined On' },
  ],
  // Superset of Attendance + Leave + Payroll columns for the consolidated
  // employee-level table — the client only ever requests the subset for
  // the modules the tenant actually selected (via the ?columns= param,
  // same mechanism every other report type already uses).
  consolidated: [
    { key: 'employeeId', label: 'Employee ID' }, { key: 'employeeName', label: 'Employee Name' },
    { key: 'department', label: 'Department' }, { key: 'designation', label: 'Designation' },
    { key: 'attendancePct', label: 'Attendance %' }, { key: 'presentDays', label: 'Present Days' },
    { key: 'lateCount', label: 'Late Count' }, { key: 'workingHours', label: 'Working Hours', format: 'hours' },
    { key: 'overtimeHours', label: 'Overtime', format: 'hours' }, { key: 'leaveTaken', label: 'Leave Taken' },
    { key: 'grossPay', label: 'Gross Pay', format: 'currency' }, { key: 'deductions', label: 'Deductions', format: 'currency' },
    { key: 'netPay', label: 'Net Pay', format: 'currency' }, { key: 'payrollStatus', label: 'Payroll Status' },
  ],
};

const REPORT_SUMMARY_BY_TYPE: Record<string, ReportSummaryFieldMeta[]> = {
  attendance: [
    { key: 'totalEmployees', label: 'Total Employees' }, { key: 'presentCount', label: 'Present' },
    { key: 'absentCount', label: 'Absent' }, { key: 'lateCount', label: 'Late' }, { key: 'halfDayCount', label: 'Half Day' },
    { key: 'totalHours', label: 'Total Hours', format: 'hours' }, { key: 'overtimeHours', label: 'Overtime', format: 'hours' },
  ],
  overtime: [
    { key: 'totalHours', label: 'Total Hours', format: 'hours' }, { key: 'overtimeHours', label: 'Total Overtime', format: 'hours' },
    { key: 'lateCount', label: 'Late Instances' },
  ],
  leave: [
    { key: 'totalLeaves', label: 'Applied' }, { key: 'approvedCount', label: 'Approved' },
    { key: 'rejectedCount', label: 'Rejected' }, { key: 'pendingCount', label: 'Pending' }, { key: 'totalDays', label: 'Total Days' },
  ],
  payroll: [
    { key: 'processedCount', label: 'Payslips' }, { key: 'totalGross', label: 'Total Gross', format: 'currency' },
    { key: 'totalDeductions', label: 'Total Deductions', format: 'currency' }, { key: 'totalPayout', label: 'Total Net Payout', format: 'currency' },
    { key: 'avgSalary', label: 'Avg. Salary', format: 'currency' },
  ],
  employee: [
    { key: 'totalEmployees', label: 'Total Employees' },
  ],
  consolidated: [
    { key: 'totalEmployees', label: 'Total Employees' }, { key: 'presentCount', label: 'Present' }, { key: 'absentCount', label: 'Absent' },
    { key: 'leaveTakenTotal', label: 'Leave Taken' }, { key: 'totalGross', label: 'Gross Pay', format: 'currency' },
    { key: 'totalDeductions', label: 'Deductions', format: 'currency' }, { key: 'totalPayout', label: 'Net Pay', format: 'currency' },
  ],
};

/**
 * GET /api/reports/data — the main Reports & Analytics data endpoint.
 * See services/reportData.ts for the actual query logic (shared with the
 * scheduled-report job handler, services/reportScheduler.ts).
 */
router.get('/api/reports/data', authenticate, async (req: any, res: any) => {
  try {
    const tenantId = req.user.tenantId;
    if (!tenantId) return res.status(400).json({ error: 'Tenant context required' });
    // No blanket privilege gate here beyond authentication — getPermittedUserIds
    // (reportData.ts) already scopes what a caller can see: a plain employee
    // is restricted to their own rows, a manager to their reports, and
    // 'reports.view'/'employee.read' holders get tenant-wide access. Payroll
    // report rows have their own additional 'payroll.read' gate inside
    // buildReportData regardless of this endpoint's scoping.

    const filters = parseFiltersFromQuery(req);
    const data = await buildReportData(tenantId, req.user, filters);
    return res.json(data);
  } catch (err: any) {
    logger.error('Error generating report data:', err);
    if (err.statusCode) return res.status(err.statusCode).json({ error: err.message });
    return sendServerError(res, err, 'reports.routes.ts (generate)');
  }
});

const ALL_COLUMN_LOOKUP: Record<string, ReportColumnMeta> = {
  employeeId: { key: 'employeeId', label: 'ID' },
  employeeName: { key: 'employeeName', label: 'Employee Name' },
  designation: { key: 'designation', label: 'Designation' },
  department: { key: 'department', label: 'Department' },
  present: { key: 'present', label: 'Present (Days)' },
  presentDays: { key: 'presentDays', label: 'Present (Days)' },
  absent: { key: 'absent', label: 'Absent (Days)' },
  absentDays: { key: 'absentDays', label: 'Absent (Days)' },
  leave: { key: 'leave', label: 'Leave (Days)' },
  leaveDays: { key: 'leaveDays', label: 'Leave (Days)' },
  workingHours: { key: 'workingHours', label: 'Hours Logged', format: 'hours' },
  attendancePct: { key: 'attendancePct', label: 'Attendance %' },
  status: { key: 'status', label: 'Status' },
  date: { key: 'date', label: 'Date' },
  checkIn: { key: 'checkIn', label: 'Check In' },
  checkOut: { key: 'checkOut', label: 'Check Out' },
  lateMins: { key: 'lateMins', label: 'Late (mins)' },
  overtimeHours: { key: 'overtimeHours', label: 'Overtime', format: 'hours' },
  isWfh: { key: 'isWfh', label: 'WFH', format: 'boolean' },
  verificationMode: { key: 'verificationMode', label: 'Attendance Mode' },
  approvalStatus: { key: 'approvalStatus', label: 'Approval Status' },
  notes: { key: 'notes', label: 'Notes' },
  leaveType: { key: 'leaveType', label: 'Leave Type' },
  startDate: { key: 'startDate', label: 'Start Date' },
  endDate: { key: 'endDate', label: 'End Date' },
  daysCount: { key: 'daysCount', label: 'Days' },
  reason: { key: 'reason', label: 'Reason' },
  appliedOn: { key: 'appliedOn', label: 'Applied On' },
  monthYear: { key: 'monthYear', label: 'Period' },
  grossSalary: { key: 'grossSalary', label: 'Gross', format: 'currency' },
  deductions: { key: 'deductions', label: 'Deductions', format: 'currency' },
  netSalary: { key: 'netSalary', label: 'Net Salary', format: 'currency' },
  lopDays: { key: 'lopDays', label: 'LOP Days' },
  pfAmount: { key: 'pfAmount', label: 'PF', format: 'currency' },
  esiAmount: { key: 'esiAmount', label: 'ESI', format: 'currency' },
  taxAmount: { key: 'taxAmount', label: 'Tax (TDS)', format: 'currency' },
  loanRecovery: { key: 'loanRecovery', label: 'Loan/Advance Recovery', format: 'currency' },
  bonusPaid: { key: 'bonusPaid', label: 'Bonus/Reimbursement', format: 'currency' },
  email: { key: 'email', label: 'Email' },
  role: { key: 'role', label: 'Role' },
  kycStatus: { key: 'kycStatus', label: 'KYC Status' },
  joinedDate: { key: 'joinedDate', label: 'Joined On' },
  grossPay: { key: 'grossPay', label: 'Gross Pay', format: 'currency' },
  netPay: { key: 'netPay', label: 'Net Pay', format: 'currency' },
  payrollStatus: { key: 'payrollStatus', label: 'Payroll Status' },
};

/**
 * GET /api/reports/export?format=pdf|xlsx — real file downloads (the CSV
 * download button is client-side, apps/admin/src/lib/csv.ts). Every export
 * (this route, and the email routes below) writes a 'REPORT_EXPORTED' row
 * to the audit ledger — "who downloaded/emailed what report, with which
 * filters, when" — the live /api/reports/data view itself is NOT audited
 * here (it fires on every filter change while browsing, which would flood
 * the ledger with noise); only an actual export/delivery is a meaningful
 * access event worth a permanent record.
 */
router.get('/api/reports/export', authenticate, async (req: any, res: any) => {
  try {
    const format = (req.query.format as string) || 'pdf';
    if (format !== 'pdf' && format !== 'xlsx') return res.status(400).json({ error: 'format must be pdf or xlsx' });

    const filters = parseFiltersFromQuery(req);
    const data = await buildReportData(req.user.tenantId, req.user, filters);
    const title = `${filters.type.charAt(0).toUpperCase()}${filters.type.slice(1)} Report`;
    const meta = await buildExportMeta(req, title, filters);

    const columnLookupType = ['leave', 'payroll', 'overtime', 'employee', 'consolidated'].includes(filters.type) ? filters.type : 'attendance';
    const allColumns = REPORT_COLUMNS_BY_TYPE[columnLookupType] || [];
    const requestedKeyList = typeof req.query.columns === 'string' && req.query.columns.length > 0
      ? req.query.columns.split(',').filter(Boolean)
      : null;
    const columns: ReportColumnMeta[] = requestedKeyList
      ? requestedKeyList.map((k) => ALL_COLUMN_LOOKUP[k] || { key: k, label: k })
      : allColumns;
    const allSummaryFields = REPORT_SUMMARY_BY_TYPE[columnLookupType] || [];
    const requestedSummaryKeys = typeof req.query.summaryFields === 'string' && req.query.summaryFields.length > 0
      ? new Set(req.query.summaryFields.split(','))
      : null;
    const summaryFields = requestedSummaryKeys ? allSummaryFields.filter((f) => requestedSummaryKeys.has(f.key)) : allSummaryFields;

    await logToAuditLedger({
      tenantId: req.user.tenantId,
      actorId: req.user.userId,
      actorName: req.user.name,
      action: 'REPORT_EXPORTED',
      details: { reportType: filters.type, format, filters: describeFilters(filters), recordCount: data.rows.length },
    });

    const filenameBase = (typeof req.query.filename === 'string' && req.query.filename.trim())
      ? req.query.filename.trim().replace(/[^a-z0-9_-]+/gi, '_')
      : title.replace(/\s+/g, '_');

    if (format === 'xlsx') {
      const buffer = await buildReportExcel(data.rows, data.summary, meta, columns, summaryFields);
      res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
      res.setHeader('Content-Disposition', `attachment; filename="${filenameBase}.xlsx"`);
      return res.send(buffer);
    }

    const buffer = await buildReportPdf(data.rows, data.summary, meta, columns, summaryFields);
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filenameBase}.pdf"`);
    return res.send(buffer);
  } catch (err: any) {
    logger.error('Error exporting report:', err);
    if (err.statusCode) return res.status(err.statusCode).json({ error: err.message });
    return sendServerError(res, err, 'reports.routes.ts (export)');
  }
});

/**
 * GET/POST /api/reports/saved-templates — real persistence
 * (report_saved_templates table), replacing the earlier in-memory-only
 * prototype that was wiped on every server restart.
 */
router.get('/api/reports/saved-templates', authenticate, async (req: any, res: any) => {
  try {
    const list = await db.select().from(schema.reportSavedTemplates)
      .where(and(eq(schema.reportSavedTemplates.tenantId, req.user.tenantId), eq(schema.reportSavedTemplates.createdByUserId, req.user.userId)))
      .orderBy(desc(schema.reportSavedTemplates.createdAt));
    return res.json({ templates: list });
  } catch (err: any) {
    return sendServerError(res, err, "reports.routes.ts");
  }
});

router.post('/api/reports/saved-templates', authenticate, async (req: any, res: any) => {
  try {
    const { name, type, filters } = req.body || {};
    if (!name) return res.status(400).json({ error: 'Template name is required' });
    const [created] = await db.insert(schema.reportSavedTemplates).values({
      tenantId: req.user.tenantId,
      createdByUserId: req.user.userId,
      name,
      reportType: type || 'attendance',
      filters: filters || {},
    }).returning();
    return res.json({ success: true, template: created });
  } catch (err: any) {
    return sendServerError(res, err, "reports.routes.ts");
  }
});

router.delete('/api/reports/saved-templates/:id', authenticate, async (req: any, res: any) => {
  try {
    const id = parseInt(req.params.id, 10);
    const rows = await db.select().from(schema.reportSavedTemplates).where(and(
      eq(schema.reportSavedTemplates.id, id),
      eq(schema.reportSavedTemplates.tenantId, req.user.tenantId),
      eq(schema.reportSavedTemplates.createdByUserId, req.user.userId),
    )).limit(1);
    if (rows.length === 0) {
      return res.status(404).json({ error: 'Template not found.' });
    }
    await db.delete(schema.reportSavedTemplates).where(eq(schema.reportSavedTemplates.id, id));
    return res.json({ success: true });
  } catch (err: any) {
    return sendServerError(res, err, "reports.routes.ts");
  }
});

/**
 * GET/POST /api/reports/schedules — real persistence (report_schedules
 * table) AND actually executed: see services/reportScheduler.ts, which
 * checks for due schedules on the existing background-scheduler tick and
 * enqueues a real job on the Postgres-backed queue (services/queue) that
 * generates the report and emails a real CSV attachment. The earlier
 * in-memory version stored config that nothing ever read.
 */
router.get('/api/reports/schedules', authenticate, async (req: any, res: any) => {
  try {
    if (!await hasPrivilege(req.user, 'reports.schedule') && !await hasPrivilege(req.user, 'reports.view')) {
      return res.status(403).json({ error: 'Access denied: Insufficient privileges.' });
    }
    const list = await db.select().from(schema.reportSchedules).where(eq(schema.reportSchedules.tenantId, req.user.tenantId)).orderBy(desc(schema.reportSchedules.createdAt));
    return res.json({ schedules: list });
  } catch (err: any) {
    return sendServerError(res, err, "reports.routes.ts");
  }
});

router.post('/api/reports/schedules', authenticate, async (req: any, res: any) => {
  try {
    if (!await hasPrivilege(req.user, 'reports.schedule')) {
      return res.status(403).json({ error: 'Access denied: Insufficient privileges.' });
    }
    const { reportName, reportType, filters, frequency, dayOfWeek, dayOfMonth, timeOfDay, recipients, format } = req.body || {};
    if (!reportName || !recipients) return res.status(400).json({ error: 'Report name and recipients are required' });
    if (!['daily', 'weekly', 'monthly'].includes(frequency)) return res.status(400).json({ error: 'frequency must be daily, weekly, or monthly' });

    const recipientList = Array.isArray(recipients) ? recipients : String(recipients).split(',').map((r: string) => r.trim()).filter(Boolean);
    const [created] = await db.insert(schema.reportSchedules).values({
      tenantId: req.user.tenantId,
      createdByUserId: req.user.userId,
      reportName,
      reportType: reportType || 'attendance',
      filters: filters || {},
      frequency,
      dayOfWeek: frequency === 'weekly' ? Number(dayOfWeek ?? 1) : null,
      dayOfMonth: frequency === 'monthly' ? Number(dayOfMonth ?? 1) : null,
      timeOfDay: timeOfDay || '08:00',
      recipients: recipientList,
      format: 'csv', // only export format actually implemented server-side today — see reportScheduler.ts
      nextRunAt: new Date(), // due immediately; the scheduler check corrects this to the real next occurrence after the first run
    }).returning();

    await logToAuditLedger({
      tenantId: req.user.tenantId,
      actorId: req.user.userId,
      actorName: req.user.name,
      action: 'REPORT_SCHEDULE_CREATED',
      details: { scheduleId: created.id, reportName, reportType: reportType || 'attendance', frequency, recipients: recipientList },
    });

    return res.json({ success: true, schedule: created });
  } catch (err: any) {
    return sendServerError(res, err, "reports.routes.ts");
  }
});

router.delete('/api/reports/schedules/:id', authenticate, async (req: any, res: any) => {
  try {
    if (!await hasPrivilege(req.user, 'reports.schedule')) {
      return res.status(403).json({ error: 'Access denied: Insufficient privileges.' });
    }
    const id = parseInt(req.params.id, 10);
    const rows = await db.select().from(schema.reportSchedules).where(and(eq(schema.reportSchedules.id, id), eq(schema.reportSchedules.tenantId, req.user.tenantId))).limit(1);
    if (rows.length === 0) return res.status(404).json({ error: 'Schedule not found.' });
    await db.delete(schema.reportSchedules).where(eq(schema.reportSchedules.id, id));
    return res.json({ success: true });
  } catch (err: any) {
    return sendServerError(res, err, "reports.routes.ts");
  }
});

/**
 * POST /api/reports/export-email — emails the CURRENTLY VIEWED report as a
 * real CSV attachment (built server-side from the same filters, so it
 * matches what's on screen), not a JSON dump of the summary object like the
 * earlier version sent.
 */
router.post('/api/reports/export-email', authenticate, async (req: any, res: any) => {
  try {
    const { recipientEmail, reportTitle, filters } = req.body || {};
    const emailTo = recipientEmail || req.user.email;
    const tenantId = req.user.tenantId;

    const data = await buildReportData(tenantId, req.user, (filters || {}) as ReportFilters);
    const csv = buildCsv(data.rows);
    const fileName = `${(reportTitle || 'report').replace(/[^a-z0-9_-]+/gi, '_')}.csv`;
    const tenantRowExport = (await db.select({ timezone: schema.tenants.timezone }).from(schema.tenants).where(eq(schema.tenants.id, tenantId)).limit(1))[0] || null;

    await sendEmail({
      to: emailTo,
      subject: `[EMS Report] ${reportTitle || 'Report Export'} (${tenantDateLabel(tenantRowExport)})`,
      text: `Hello,\n\nYour requested report "${reportTitle}" is attached as a CSV.\n\nGenerated by: ${req.user.email}\nDate: ${tenantDateTimeLabel(tenantRowExport)}\nRecords: ${data.rows.length}\n\nBest regards,\nSmart Teams EMS`,
      html: `<div style="font-family: sans-serif; padding: 20px; border: 1px solid #e2e8f0; border-radius: 8px;">
        <h2 style="color: #1e293b; margin-top: 0;">Smart Teams Operational Report</h2>
        <p style="font-size: 14px; color: #64748b;">Report: <strong>${reportTitle}</strong></p>
        <p style="font-size: 14px; color: #64748b;">Generated On: ${tenantDateTimeLabel(tenantRowExport)}</p>
        <p style="font-size: 14px; color: #64748b;">Requested By: ${req.user.email}</p>
        <p style="font-size: 14px; color: #64748b;">${data.rows.length} record(s) attached as CSV.</p>
        <p style="font-size: 12px; color: #94a3b8;">Confidential document — generated automatically by Smart Teams EMS.</p>
      </div>`,
      attachments: [{ filename: fileName, content: csv, contentType: 'text/csv' }],
    });

    await logToAuditLedger({
      tenantId,
      actorId: req.user.userId,
      actorName: req.user.name,
      action: 'REPORT_EXPORTED',
      details: { reportType: (filters || {}).type || 'attendance', format: 'csv', emailedTo: emailTo, recordCount: data.rows.length },
    });

    return res.json({ success: true, message: `Report sent to ${emailTo}`, recordCount: data.rows.length });
  } catch (err: any) {
    return sendServerError(res, err, 'reports.routes.ts (email)');
  }
});
