-- Reserved migration number. The original draft attempted CREATE INDEX
-- CONCURRENTLY here, but Drizzle executes migrations transactionally and the
-- payroll extension tables do not exist until 0011. Migration 0011 creates
-- these hot-path indexes after all of their tables exist.
