-- Reserved migration number. Migration 0011 creates attendance_preferences
-- and adds payroll_settings.payroll_locking_enabled, so applying either
-- change here would reference a table that does not exist yet or duplicate
-- the later generated migration.
