-- Reserved migration number. Migration 0011 contains the generated
-- break_sessions constraint and both foreign keys. Applying them here first
-- makes 0011 fail with duplicate-constraint errors on a fresh database.
